name: planly-telegram-bot
region: ams
workers:
  - name: telegram-bot
    dockerfile_path: /telegram-bot/Dockerfile
    source_dir: /telegram-bot
    github:
      repo: your-github-username/planly
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: TELEGRAM_BOT_TOKEN
        value: "CHANGE_ME"
        type: SECRET
      - key: WEBSERVER_URL
        value: "https://your-backend-url.ondigitalocean.app"
      - key: SERVICE_TOKEN
        value: "CHANGE_ME"
        type: SECRET
